### ISSUE TITLE
Getting an error when using this oauth program in an external js module

### ISSUE THREAD

**Issue by louischausse** [HubSpot/oauth-quickstart-nodejs#10]
Hello,

When I try to store the oauth program in a js module outside of the main index.js I get an error.

I created the oauth.js file:

```require('dotenv').config();
const express = require('express');
const request = require('request-promise-native');
const NodeCache = require('node-cache');
const session = require('express-session');

const PORT = 3000;
const app = express();

const CLIENT_ID = process.env.CLIENT_ID;
const CLIENT_SECRET = process.env.CLIENT_SECRET;
// Supports a list of scopes as a string delimited by ',' or ' ' or '%20'
const SCOPES = (process.env.SCOPE.split(/ |, ?|%20/) || ['contacts']).join(' ');

const REDIRECT_URI = `http://localhost:${PORT}/oauth-callback`;

const refreshTokenStore = {};
const accessTokenCache = new NodeCache({ deleteOnExpire: true });

// Use a session to keep track of client ID
app.use(session({
  secret: Math.random().toString(36).substring(2),
  resave: false,
  saveUninitialized: true
}));

//================================//
//   Running the OAuth 2.0 Flow   //
//================================//

// Step 1
// Build the authorization URL to redirect a user
// to when they choose to install the app
const authUrl =
  'https://app.hubspot.com/oauth/authorize' +
  `?client_id=${encodeURIComponent(CLIENT_ID)}` + // app's client ID
  `&scope=${encodeURIComponent(SCOPES)}` + // scopes being requested by the app
  `&redirect_uri=${encodeURIComponent(REDIRECT_URI)}`; // where to send the user after the consent page

// Redirect the user from the installation page to
// the authorization URL
module.exports = function(app){
app.get('/install', (req, res) => {
  console.log('Initiating OAuth 2.0 flow with HubSpot');
  console.log("Step 1: Redirecting user to HubSpot's OAuth 2.0 server");
  res.redirect(authUrl);
  console.log('Step 2: User is being prompted for consent by HubSpot');
});

// Step 2
// The user is prompted to give the app access to the requested
// resources. This is all done by HubSpot, so no work is necessary
// on the app's end

// Step 3
// Receive the authorization code from the OAuth 2.0 Server,
// and process it based on the query parameters that are passed
app.get('/oauth-callback', async (req, res) => {
  console.log('Step 3: Handling the request sent by the server');

  // Received a user authorization code, so now combine that with the other
  // required values and exchange both for an access token and a refresh token
  if (req.query.code) {
    console.log('  > Received an authorization token');

    const authCodeProof = {
      grant_type: 'authorization_code',
      client_id: CLIENT_ID,
      client_secret: CLIENT_SECRET,
      redirect_uri: REDIRECT_URI,
      code: req.query.code
    };

    // Step 4
    // Exchange the authorization code for an access token and refresh token
    console.log('Step 4: Exchanging authorization code for an access token and refresh token');
    const token = await exchangeForTokens(req.sessionID, authCodeProof);
    if (token.message) {
      return res.redirect(`/error?msg=${token.message}`);
    }

    // Once the tokens have been retrieved, use them to make a query
    // to the HubSpot API
    res.redirect(`/`);
  }
});
}
//==========================================//
//   Exchanging Proof for an Access Token   //
//==========================================//

const exchangeForTokens = async (userId, exchangeProof) => {
  try {
    const responseBody = await request.post('https://api.hubapi.com/oauth/v1/token', {
      form: exchangeProof
    });
    // Usually, this token data should be persisted in a database and associated with
    // a user identity.
    const tokens = JSON.parse(responseBody);
    refreshTokenStore[userId] = tokens.refresh_token;
    accessTokenCache.set(userId, tokens.access_token, Math.round(tokens.expires_in * 0.75));

    console.log('  > Received an access token and refresh token');
    return tokens.access_token;
  } catch (e) {
    console.error(`  > Error exchanging ${exchangeProof.grant_type} for access token`);
    return JSON.parse(e.response.body);
  }
};

const refreshAccessToken = async (userId) => {
  const refreshTokenProof = {
    grant_type: 'refresh_token',
    client_id: CLIENT_ID,
    client_secret: CLIENT_SECRET,
    redirect_uri: REDIRECT_URI,
    refresh_token: refreshTokenStore[userId]
  };
  return await exchangeForTokens(userId, refreshTokenProof);
};

const getAccessToken = async (userId) => {
  // If the access token has expired, retrieve
  // a new one using the refresh token
  if (!accessTokenCache.get(userId)) {
    console.log('Refreshing expired access token');
    await refreshAccessToken(userId);
  }
  return accessTokenCache.get(userId);
};

global.isAuthorized = (userId) => {
  return refreshTokenStore[userId] ? true : false;
};
```
That I require in index.js like this:
```
require('dotenv').config();
const express = require('express');
const request = require('request-promise-native');

const PORT = 3000;
const app = express();


//================================//
//   Running the OAuth 2.0 Flow   //
//================================//

require('./oauth.js')(app);

//====================================================//
//   Using an Access Token to Query the HubSpot API   //
//====================================================//

const getContact = async (accessToken) => {
  console.log('Retrieving a contact from HubSpot using an access token');
  try {
    const headers = {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json'
    };
    const result = await request.get('https://api.hubapi.com/contacts/v1/lists/all/contacts/all?count=1', {
      headers: headers
    });

    return JSON.parse(result).contacts[0];
  } catch (e) {
    console.error('  > Unable to retrieve contact');
    return JSON.parse(e.response.body);
  }
};
```
And this it the output I get:
```
Initiating OAuth 2.0 flow with HubSpot
Step 1: Redirecting user to HubSpot's OAuth 2.0 server
Step 2: User is being prompted for consent by HubSpot
Step 3: Handling the request sent by the server
  > Received an authorization token
Step 4: Exchanging authorization code for an access token and refresh token
  > Error exchanging authorization_code for access token
(node:4747) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
    at exchangeForTokens (/home/louischausse/hubspot-integrations/hubspot-tapfiliate-integration/app/oauth.js:107:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4747) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4747) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Step 3: Handling the request sent by the server
  > Received an authorization token
Step 4: Exchanging authorization code for an access token and refresh token
  > Error exchanging authorization_code for access token
(node:4747) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
    at exchangeForTokens (/home/louischausse/hubspot-integrations/hubspot-tapfiliate-integration/app/oauth.js:107:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4747) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Step 3: Handling the request sent by the server
  > Received an authorization token
Step 4: Exchanging authorization code for an access token and refresh token
  > Error exchanging authorization_code for access token
(node:4747) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
    at exchangeForTokens (/home/louischausse/hubspot-integrations/hubspot-tapfiliate-integration/app/oauth.js:107:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4747) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
Step 3: Handling the request sent by the server
  > Received an authorization token
Step 4: Exchanging authorization code for an access token and refresh token
  > Error exchanging authorization_code for access token
(node:4747) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
    at exchangeForTokens (/home/louischausse/hubspot-integrations/hubspot-tapfiliate-integration/app/oauth.js:107:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4747) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Comment by egoodhall** [comment]
Hey @louischausse, thanks for reaching out - issues on this repository are used for tracking issues and questions related to the code that's checked into the source control. Since this one has to do with debugging a modified version of the code in this repository, I'm going to close it.

---
That being said, it looks like there's 1 error happening a few times in your output:
```
(node:4747) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
    at exchangeForTokens (/home/louischausse/hubspot-integrations/hubspot-tapfiliate-integration/app/oauth.js:107:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4747) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
This is coming from [this line](https://github.com/HubSpot/oauth-quickstart-nodejs/blob/master/index.js#L106) in the original code, and it looks like the authorization code/token exchange is throwing an error that doesn't have a `response` field on it. A possible cause could be that the `app` you are working with in the exported function isn't being set up to use the `sessions` middleware (that's being done [outside the exported function](https://github.com/HubSpot/oauth-quickstart-nodejs/blob/master/index.js#L21)), but a forum for debugging/Node JS questions might be a better place to get further help on something like this.

**Comment by louischausse** [comment]
@emm035 That's it! You made me realized what was my mistake!

Thanks!
