### ISSUE TITLE
Error exchanging refresh_token for access token

### ISSUE THREAD

**Issue by louischausse** [HubSpot/oauth-quickstart-nodejs#16]
I got this error when calling `getAccessToken` a while a after the app is connected to a HubSpot portal

it looks like the "refresh Token" part of this app isn't working properly...

`2019-12-13T18:32:26.786736+00:00 app[web.1]: Refreshing expired access token
2019-12-13T18:32:26.873302+00:00 app[web.1]:        > Error exchanging refresh_token for access token
2019-12-13T18:32:27.048973+00:00 app[web.1]: Error: Request failed with status code 401
2019-12-13T18:32:27.048987+00:00 app[web.1]:     at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
2019-12-13T18:32:27.048989+00:00 app[web.1]:     at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
2019-12-13T18:32:27.048992+00:00 app[web.1]:     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:237:11)
2019-12-13T18:32:27.048994+00:00 app[web.1]:     at IncomingMessage.emit (events.js:215:7)
2019-12-13T18:32:27.048996+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1184:12)
2019-12-13T18:32:27.048998+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
2019-12-13T18:32:27.049001+00:00 app[web.1]:   config: {
2019-12-13T18:32:27.049003+00:00 app[web.1]:     url: 'https://api.hubapi.com/deals/v1/deal/1276965455',
2019-12-13T18:32:27.049005+00:00 app[web.1]:     method: 'get',
2019-12-13T18:32:27.049007+00:00 app[web.1]:     headers: {
2019-12-13T18:32:27.049009+00:00 app[web.1]:       Accept: 'application/json, text/plain, */*',
2019-12-13T18:32:27.049012+00:00 app[web.1]:       Authorization: 'Bearer undefined',
2019-12-13T18:32:27.049014+00:00 app[web.1]:       'Content-Type': 'application/json',
2019-12-13T18:32:27.049016+00:00 app[web.1]:       'User-Agent': 'axios/0.19.0'
2019-12-13T18:32:27.049018+00:00 app[web.1]:     },
2019-12-13T18:32:27.049020+00:00 app[web.1]:     transformRequest: [ [Function: transformRequest] ],
2019-12-13T18:32:27.049022+00:00 app[web.1]:     transformResponse: [ [Function: transformResponse] ],
2019-12-13T18:32:27.049024+00:00 app[web.1]:     timeout: 0,
2019-12-13T18:32:27.049026+00:00 app[web.1]:     adapter: [Function: httpAdapter],
2019-12-13T18:32:27.049028+00:00 app[web.1]:     xsrfCookieName: 'XSRF-TOKEN',
2019-12-13T18:32:27.049030+00:00 app[web.1]:     xsrfHeaderName: 'X-XSRF-TOKEN',
2019-12-13T18:32:27.049032+00:00 app[web.1]:     maxContentLength: -1,
2019-12-13T18:32:27.049034+00:00 app[web.1]:     validateStatus: [Function: validateStatus],
2019-12-13T18:32:27.049036+00:00 app[web.1]:     data: undefined
2019-12-13T18:32:27.049038+00:00 app[web.1]:   },
2019-12-13T18:32:27.049040+00:00 app[web.1]:   request: ClientRequest {
2019-12-13T18:32:27.049042+00:00 app[web.1]:     _events: [Object: null prototype] {
2019-12-13T18:32:27.049044+00:00 app[web.1]:       socket: [Function],
2019-12-13T18:32:27.049046+00:00 app[web.1]:       abort: [Function],
2019-12-13T18:32:27.049048+00:00 app[web.1]:       aborted: [Function],
2019-12-13T18:32:27.049050+00:00 app[web.1]:       error: [Function],
2019-12-13T18:32:27.049052+00:00 app[web.1]:       timeout: [Function],
2019-12-13T18:32:27.049054+00:00 app[web.1]:       prefinish: [Function: requestOnPrefinish]
2019-12-13T18:32:27.049056+00:00 app[web.1]:     },
2019-12-13T18:32:27.049058+00:00 app[web.1]:     _eventsCount: 6,
2019-12-13T18:32:27.049059+00:00 app[web.1]:     _maxListeners: undefined,
2019-12-13T18:32:27.049061+00:00 app[web.1]:     outputData: [],
2019-12-13T18:32:27.049063+00:00 app[web.1]:     outputSize: 0,
2019-12-13T18:32:27.049065+00:00 app[web.1]:     writable: true,
2019-12-13T18:32:27.049067+00:00 app[web.1]:     _last: true,
2019-12-13T18:32:27.049069+00:00 app[web.1]:     chunkedEncoding: false,
2019-12-13T18:32:27.049071+00:00 app[web.1]:     shouldKeepAlive: false,
2019-12-13T18:32:27.049073+00:00 app[web.1]:     useChunkedEncodingByDefault: false,
2019-12-13T18:32:27.049075+00:00 app[web.1]:     sendDate: false,
2019-12-13T18:32:27.049077+00:00 app[web.1]:     _removedConnection: false,
2019-12-13T18:32:27.049079+00:00 app[web.1]:     _removedContLen: false,
2019-12-13T18:32:27.049081+00:00 app[web.1]:     _removedTE: false,
2019-12-13T18:32:27.049083+00:00 app[web.1]:     _contentLength: 0,
2019-12-13T18:32:27.049085+00:00 app[web.1]:     _hasBody: true,
2019-12-13T18:32:27.049087+00:00 app[web.1]:     _trailer: '',
2019-12-13T18:32:27.049089+00:00 app[web.1]:     finished: true,
2019-12-13T18:32:27.049090+00:00 app[web.1]:     _headerSent: true,
2019-12-13T18:32:27.049092+00:00 app[web.1]:     socket: TLSSocket {
2019-12-13T18:32:27.049094+00:00 app[web.1]:       _tlsOptions: [Object],
2019-12-13T18:32:27.049096+00:00 app[web.1]:       _secureEstablished: true,
2019-12-13T18:32:27.049098+00:00 app[web.1]:       _securePending: false,
2019-12-13T18:32:27.049100+00:00 app[web.1]:       _newSessionPending: false,
2019-12-13T18:32:27.049102+00:00 app[web.1]:       _controlReleased: true,
2019-12-13T18:32:27.049104+00:00 app[web.1]:       _SNICallback: null,
2019-12-13T18:32:27.049106+00:00 app[web.1]:       servername: 'api.hubapi.com',
2019-12-13T18:32:27.049108+00:00 app[web.1]:       alpnProtocol: false,
2019-12-13T18:32:27.049110+00:00 app[web.1]:       authorized: true,
2019-12-13T18:32:27.049112+00:00 app[web.1]:       authorizationError: null,
2019-12-13T18:32:27.049114+00:00 app[web.1]:       encrypted: true,
2019-12-13T18:32:27.049116+00:00 app[web.1]:       _events: [Object: null prototype],
2019-12-13T18:32:27.049118+00:00 app[web.1]:       _eventsCount: 9,
2019-12-13T18:32:27.049123+00:00 app[web.1]:       connecting: false,
2019-12-13T18:32:27.049125+00:00 app[web.1]:       _hadError: false,
2019-12-13T18:32:27.049127+00:00 app[web.1]:       _parent: null,
2019-12-13T18:32:27.049129+00:00 app[web.1]:       _host: 'api.hubapi.com',
2019-12-13T18:32:27.049131+00:00 app[web.1]:       _readableState: [ReadableState],
2019-12-13T18:32:27.049133+00:00 app[web.1]:       readable: true,
2019-12-13T18:32:27.049135+00:00 app[web.1]:       _maxListeners: undefined,
2019-12-13T18:32:27.049137+00:00 app[web.1]:       _writableState: [WritableState],
2019-12-13T18:32:27.049139+00:00 app[web.1]:       writable: false,
2019-12-13T18:32:27.049141+00:00 app[web.1]:       allowHalfOpen: false,
2019-12-13T18:32:27.049143+00:00 app[web.1]:       _sockname: null,
2019-12-13T18:32:27.049145+00:00 app[web.1]:       _pendingData: null,
2019-12-13T18:32:27.049147+00:00 app[web.1]:       _pendingEncoding: '',
2019-12-13T18:32:27.049149+00:00 app[web.1]:       server: undefined,
2019-12-13T18:32:27.049151+00:00 app[web.1]:       _server: null,
2019-12-13T18:32:27.049153+00:00 app[web.1]:       ssl: [TLSWrap],
2019-12-13T18:32:27.049154+00:00 app[web.1]:       _requestCert: true,
2019-12-13T18:32:27.049156+00:00 app[web.1]:       _rejectUnauthorized: true,
2019-12-13T18:32:27.049159+00:00 app[web.1]:       parser: null,
2019-12-13T18:32:27.049161+00:00 app[web.1]:       _httpMessage: [Circular],
2019-12-13T18:32:27.049163+00:00 app[web.1]:       [Symbol(res)]: [TLSWrap],
2019-12-13T18:32:27.049164+00:00 app[web.1]:       [Symbol(asyncId)]: 198,
2019-12-13T18:32:27.049167+00:00 app[web.1]:       [Symbol(kHandle)]: [TLSWrap],
2019-12-13T18:32:27.049169+00:00 app[web.1]:       [Symbol(lastWriteQueueSize)]: 0,
2019-12-13T18:32:27.049171+00:00 app[web.1]:       [Symbol(timeout)]: null,
2019-12-13T18:32:27.049172+00:00 app[web.1]:       [Symbol(kBuffer)]: null,
2019-12-13T18:32:27.049174+00:00 app[web.1]:       [Symbol(kBufferCb)]: null,
2019-12-13T18:32:27.049176+00:00 app[web.1]:       [Symbol(kBufferGen)]: null,
2019-12-13T18:32:27.049178+00:00 app[web.1]:       [Symbol(kBytesRead)]: 0,
2019-12-13T18:32:27.049180+00:00 app[web.1]:       [Symbol(kBytesWritten)]: 0,
2019-12-13T18:32:27.049182+00:00 app[web.1]:       [Symbol(connect-options)]: [Object]
2019-12-13T18:32:27.049184+00:00 app[web.1]:     },
2019-12-13T18:32:27.049186+00:00 app[web.1]:     connection: TLSSocket {
2019-12-13T18:32:27.049188+00:00 app[web.1]:       _tlsOptions: [Object],
2019-12-13T18:32:27.049190+00:00 app[web.1]:       _secureEstablished: true,
2019-12-13T18:32:27.049192+00:00 app[web.1]:       _securePending: false,
2019-12-13T18:32:27.049194+00:00 app[web.1]:       _newSessionPending: false,
2019-12-13T18:32:27.049196+00:00 app[web.1]:       _controlReleased: true,
2019-12-13T18:32:27.049198+00:00 app[web.1]:       _SNICallback: null,
2019-12-13T18:32:27.049200+00:00 app[web.1]:       servername: 'api.hubapi.com',
2019-12-13T18:32:27.049202+00:00 app[web.1]:       alpnProtocol: false,
2019-12-13T18:32:27.049203+00:00 app[web.1]:       authorized: true,
2019-12-13T18:32:27.049206+00:00 app[web.1]:       authorizationError: null,
2019-12-13T18:32:27.049208+00:00 app[web.1]:       encrypted: true,
2019-12-13T18:32:27.049210+00:00 app[web.1]:       _events: [Object: null prototype],
2019-12-13T18:32:27.049212+00:00 app[web.1]:       _eventsCount: 9,
2019-12-13T18:32:27.049214+00:00 app[web.1]:       connecting: false,
2019-12-13T18:32:27.049215+00:00 app[web.1]:       _hadError: false,
2019-12-13T18:32:27.049217+00:00 app[web.1]:       _parent: null,
2019-12-13T18:32:27.049219+00:00 app[web.1]:       _host: 'api.hubapi.com',
2019-12-13T18:32:27.049221+00:00 app[web.1]:       _readableState: [ReadableState],
2019-12-13T18:32:27.049223+00:00 app[web.1]:       readable: true,
2019-12-13T18:32:27.049225+00:00 app[web.1]:       _maxListeners: undefined,
2019-12-13T18:32:27.049227+00:00 app[web.1]:       _writableState: [WritableState],
2019-12-13T18:32:27.049229+00:00 app[web.1]:       writable: false,
2019-12-13T18:32:27.049231+00:00 app[web.1]:       allowHalfOpen: false,
2019-12-13T18:32:27.049233+00:00 app[web.1]:       _sockname: null,
2019-12-13T18:32:27.049235+00:00 app[web.1]:       _pendingData: null,
2019-12-13T18:32:27.049237+00:00 app[web.1]:       _pendingEncoding: '',
2019-12-13T18:32:27.049239+00:00 app[web.1]:       server: undefined,
2019-12-13T18:32:27.049241+00:00 app[web.1]:       _server: null,
2019-12-13T18:32:27.049242+00:00 app[web.1]:       ssl: [TLSWrap],
2019-12-13T18:32:27.049244+00:00 app[web.1]:       _requestCert: true,
2019-12-13T18:32:27.049246+00:00 app[web.1]:       _rejectUnauthorized: true,
2019-12-13T18:32:27.049248+00:00 app[web.1]:       parser: null,
2019-12-13T18:32:27.049250+00:00 app[web.1]:       _httpMessage: [Circular],
2019-12-13T18:32:27.049252+00:00 app[web.1]:       [Symbol(res)]: [TLSWrap],
2019-12-13T18:32:27.049254+00:00 app[web.1]:       [Symbol(asyncId)]: 198,
2019-12-13T18:32:27.049262+00:00 app[web.1]:       [Symbol(kHandle)]: [TLSWrap],
2019-12-13T18:32:27.049264+00:00 app[web.1]:       [Symbol(lastWriteQueueSize)]: 0,
2019-12-13T18:32:27.049266+00:00 app[web.1]:       [Symbol(timeout)]: null,
2019-12-13T18:32:27.049268+00:00 app[web.1]:       [Symbol(kBuffer)]: null,
2019-12-13T18:32:27.049269+00:00 app[web.1]:       [Symbol(kBufferCb)]: null,
2019-12-13T18:32:27.049271+00:00 app[web.1]:       [Symbol(kBufferGen)]: null,
2019-12-13T18:32:27.049273+00:00 app[web.1]:       [Symbol(kBytesRead)]: 0,
2019-12-13T18:32:27.049275+00:00 app[web.1]:       [Symbol(kBytesWritten)]: 0,
2019-12-13T18:32:27.049277+00:00 app[web.1]:       [Symbol(connect-options)]: [Object]
2019-12-13T18:32:27.049279+00:00 app[web.1]:     },
2019-12-13T18:32:27.049281+00:00 app[web.1]:     _header: 'GET /deals/v1/deal/1276965455 HTTP/1.1\r\n' +
2019-12-13T18:32:27.049283+00:00 app[web.1]:       'Accept: application/json, text/plain, */*\r\n' +
2019-12-13T18:32:27.049285+00:00 app[web.1]:       'Authorization: Bearer undefined\r\n' +
2019-12-13T18:32:27.049287+00:00 app[web.1]:       'Content-Type: application/json\r\n' +
2019-12-13T18:32:27.049289+00:00 app[web.1]:       'User-Agent: axios/0.19.0\r\n' +
2019-12-13T18:32:27.049291+00:00 app[web.1]:       'Host: api.hubapi.com\r\n' +
2019-12-13T18:32:27.049293+00:00 app[web.1]:       'Connection: close\r\n' +
2019-12-13T18:32:27.049295+00:00 app[web.1]:       '\r\n',
2019-12-13T18:32:27.049297+00:00 app[web.1]:     _onPendingData: [Function: noopPendingOutput],
2019-12-13T18:32:27.049299+00:00 app[web.1]:     agent: Agent {
2019-12-13T18:32:27.049301+00:00 app[web.1]:       _events: [Object: null prototype],
2019-12-13T18:32:27.049303+00:00 app[web.1]:       _eventsCount: 1,
2019-12-13T18:32:27.049305+00:00 app[web.1]:       _maxListeners: undefined,
2019-12-13T18:32:27.049307+00:00 app[web.1]:       defaultPort: 443,
2019-12-13T18:32:27.049309+00:00 app[web.1]:       protocol: 'https:',
2019-12-13T18:32:27.049311+00:00 app[web.1]:       options: [Object],
2019-12-13T18:32:27.049312+00:00 app[web.1]:       requests: {},
2019-12-13T18:32:27.049314+00:00 app[web.1]:       sockets: [Object],
2019-12-13T18:32:27.049316+00:00 app[web.1]:       freeSockets: {},
2019-12-13T18:32:27.049318+00:00 app[web.1]:       keepAliveMsecs: 1000,
2019-12-13T18:32:27.049321+00:00 app[web.1]:       keepAlive: false,
2019-12-13T18:32:27.049322+00:00 app[web.1]:       maxSockets: Infinity,
2019-12-13T18:32:27.049324+00:00 app[web.1]:       maxFreeSockets: 256,
2019-12-13T18:32:27.049326+00:00 app[web.1]:       maxCachedSessions: 100,
2019-12-13T18:32:27.049328+00:00 app[web.1]:       _sessionCache: [Object]
2019-12-13T18:32:27.049330+00:00 app[web.1]:     },
2019-12-13T18:32:27.049332+00:00 app[web.1]:     socketPath: undefined,
2019-12-13T18:32:27.049334+00:00 app[web.1]:     method: 'GET',
2019-12-13T18:32:27.049336+00:00 app[web.1]:     path: '/deals/v1/deal/1276965455',
2019-12-13T18:32:27.049338+00:00 app[web.1]:     _ended: true,
2019-12-13T18:32:27.049340+00:00 app[web.1]:     res: IncomingMessage {
2019-12-13T18:32:27.049342+00:00 app[web.1]:       _readableState: [ReadableState],
2019-12-13T18:32:27.049344+00:00 app[web.1]:       readable: false,
2019-12-13T18:32:27.049346+00:00 app[web.1]:       _events: [Object: null prototype],
2019-12-13T18:32:27.049348+00:00 app[web.1]:       _eventsCount: 3,
2019-12-13T18:32:27.049350+00:00 app[web.1]:       _maxListeners: undefined,
2019-12-13T18:32:27.049352+00:00 app[web.1]:       socket: [TLSSocket],
2019-12-13T18:32:27.049354+00:00 app[web.1]:       connection: [TLSSocket],
2019-12-13T18:32:27.049356+00:00 app[web.1]:       httpVersionMajor: 1,
2019-12-13T18:32:27.049358+00:00 app[web.1]:       httpVersionMinor: 1,
2019-12-13T18:32:27.049360+00:00 app[web.1]:       httpVersion: '1.1',
2019-12-13T18:32:27.049362+00:00 app[web.1]:       complete: true,
2019-12-13T18:32:27.049364+00:00 app[web.1]:       headers: [Object],
2019-12-13T18:32:27.049365+00:00 app[web.1]:       rawHeaders: [Array],
2019-12-13T18:32:27.049367+00:00 app[web.1]:       trailers: {},
2019-12-13T18:32:27.049369+00:00 app[web.1]:       rawTrailers: [],
2019-12-13T18:32:27.049371+00:00 app[web.1]:       aborted: false,
2019-12-13T18:32:27.049373+00:00 app[web.1]:       upgrade: false,
2019-12-13T18:32:27.049375+00:00 app[web.1]:       url: '',
2019-12-13T18:32:27.049377+00:00 app[web.1]:       method: null,
2019-12-13T18:32:27.049379+00:00 app[web.1]:       statusCode: 401,
2019-12-13T18:32:27.049381+00:00 app[web.1]:       statusMessage: 'Unauthorized',
2019-12-13T18:32:27.049383+00:00 app[web.1]:       client: [TLSSocket],
2019-12-13T18:32:27.049385+00:00 app[web.1]:       _consuming: true,
2019-12-13T18:32:27.049388+00:00 app[web.1]:       _dumped: false,
2019-12-13T18:32:27.049390+00:00 app[web.1]:       req: [Circular],
2019-12-13T18:32:27.049392+00:00 app[web.1]:       responseUrl: 'https://api.hubapi.com/deals/v1/deal/1276965455',
2019-12-13T18:32:27.049394+00:00 app[web.1]:       redirects: []
2019-12-13T18:32:27.049396+00:00 app[web.1]:     },
2019-12-13T18:32:27.049397+00:00 app[web.1]:     aborted: false,
2019-12-13T18:32:27.049399+00:00 app[web.1]:     timeoutCb: null,
2019-12-13T18:32:27.049401+00:00 app[web.1]:     upgradeOrConnect: false,
2019-12-13T18:32:27.049403+00:00 app[web.1]:     parser: null,
2019-12-13T18:32:27.049405+00:00 app[web.1]:     maxHeadersCount: null,
2019-12-13T18:32:27.049407+00:00 app[web.1]:     _redirectable: Writable {
2019-12-13T18:32:27.049409+00:00 app[web.1]:       _writableState: [WritableState],
2019-12-13T18:32:27.049411+00:00 app[web.1]:       writable: true,
2019-12-13T18:32:27.049413+00:00 app[web.1]:       _events: [Object: null prototype],
2019-12-13T18:32:27.049415+00:00 app[web.1]:       _eventsCount: 2,
2019-12-13T18:32:27.049417+00:00 app[web.1]:       _maxListeners: undefined,
2019-12-13T18:32:27.049419+00:00 app[web.1]:       _options: [Object],
2019-12-13T18:32:27.049421+00:00 app[web.1]:       _redirectCount: 0,
2019-12-13T18:32:27.049423+00:00 app[web.1]:       _redirects: [],
2019-12-13T18:32:27.049425+00:00 app[web.1]:       _requestBodyLength: 0,
2019-12-13T18:32:27.049427+00:00 app[web.1]:       _requestBodyBuffers: [],
2019-12-13T18:32:27.049429+00:00 app[web.1]:       _onNativeResponse: [Function],
2019-12-13T18:32:27.049431+00:00 app[web.1]:       _currentRequest: [Circular],
2019-12-13T18:32:27.049433+00:00 app[web.1]:       _currentUrl: 'https://api.hubapi.com/deals/v1/deal/1276965455'
2019-12-13T18:32:27.049435+00:00 app[web.1]:     },
2019-12-13T18:32:27.049445+00:00 app[web.1]:     [Symbol(kNeedDrain)]: false,
2019-12-13T18:32:27.049448+00:00 app[web.1]:     [Symbol(isCorked)]: false,
2019-12-13T18:32:27.049450+00:00 app[web.1]:     [Symbol(kOutHeaders)]: [Object: null prototype] {
2019-12-13T18:32:27.049452+00:00 app[web.1]:       accept: [Array],
2019-12-13T18:32:27.049454+00:00 app[web.1]:       authorization: [Array],
2019-12-13T18:32:27.049456+00:00 app[web.1]:       'content-type': [Array],
2019-12-13T18:32:27.049458+00:00 app[web.1]:       'user-agent': [Array],
2019-12-13T18:32:27.049460+00:00 app[web.1]:       host: [Array]
2019-12-13T18:32:27.049462+00:00 app[web.1]:     }
2019-12-13T18:32:27.049464+00:00 app[web.1]:   },
2019-12-13T18:32:27.049466+00:00 app[web.1]:   response: {
2019-12-13T18:32:27.049468+00:00 app[web.1]:     status: 401,
2019-12-13T18:32:27.049470+00:00 app[web.1]:     statusText: 'Unauthorized',
2019-12-13T18:32:27.049472+00:00 app[web.1]:     headers: {
2019-12-13T18:32:27.049474+00:00 app[web.1]:       date: 'Fri, 13 Dec 2019 18:32:26 GMT',
2019-12-13T18:32:27.049476+00:00 app[web.1]:       'content-type': 'application/json;charset=utf-8',
2019-12-13T18:32:27.049478+00:00 app[web.1]:       'content-length': '701',
2019-12-13T18:32:27.049480+00:00 app[web.1]:       connection: 'close',
2019-12-13T18:32:27.049482+00:00 app[web.1]:       'set-cookie': [Array],
2019-12-13T18:32:27.049484+00:00 app[web.1]:       'x-trace': '2B8B6836F4C3A0516EC4B2605F48BA51DFADF86300000000000000000000',
2019-12-13T18:32:27.049486+00:00 app[web.1]:       vary: 'Accept-Encoding',
2019-12-13T18:32:27.049488+00:00 app[web.1]:       'access-control-allow-credentials': 'false',
2019-12-13T18:32:27.049490+00:00 app[web.1]:       'cf-cache-status': 'DYNAMIC',
2019-12-13T18:32:27.049492+00:00 app[web.1]:       'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
2019-12-13T18:32:27.049494+00:00 app[web.1]:       'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
2019-12-13T18:32:27.049496+00:00 app[web.1]:       server: 'cloudflare',
2019-12-13T18:32:27.049498+00:00 app[web.1]:       'cf-ray': '544a05509f2ae11e-IAD'
2019-12-13T18:32:27.049500+00:00 app[web.1]:     },
2019-12-13T18:32:27.049502+00:00 app[web.1]:     config: {
2019-12-13T18:32:27.049504+00:00 app[web.1]:       url: 'https://api.hubapi.com/deals/v1/deal/1276965455',
2019-12-13T18:32:27.049506+00:00 app[web.1]:       method: 'get',
2019-12-13T18:32:27.049508+00:00 app[web.1]:       headers: [Object],
2019-12-13T18:32:27.049510+00:00 app[web.1]:       transformRequest: [Array],
2019-12-13T18:32:27.049513+00:00 app[web.1]:       transformResponse: [Array],
2019-12-13T18:32:27.049515+00:00 app[web.1]:       timeout: 0,
2019-12-13T18:32:27.049517+00:00 app[web.1]:       adapter: [Function: httpAdapter],
2019-12-13T18:32:27.049519+00:00 app[web.1]:       xsrfCookieName: 'XSRF-TOKEN',
2019-12-13T18:32:27.049521+00:00 app[web.1]:       xsrfHeaderName: 'X-XSRF-TOKEN',
2019-12-13T18:32:27.049524+00:00 app[web.1]:       maxContentLength: -1,
2019-12-13T18:32:27.049526+00:00 app[web.1]:       validateStatus: [Function: validateStatus],
2019-12-13T18:32:27.049528+00:00 app[web.1]:       data: undefined
2019-12-13T18:32:27.049530+00:00 app[web.1]:     },
2019-12-13T18:32:27.049532+00:00 app[web.1]:     request: ClientRequest {
2019-12-13T18:32:27.049534+00:00 app[web.1]:       _events: [Object: null prototype],
2019-12-13T18:32:27.049542+00:00 app[web.1]:       _eventsCount: 6,
2019-12-13T18:32:27.049544+00:00 app[web.1]:       _maxListeners: undefined,
2019-12-13T18:32:27.049546+00:00 app[web.1]:       outputData: [],
2019-12-13T18:32:27.049549+00:00 app[web.1]:       outputSize: 0,
2019-12-13T18:32:27.049550+00:00 app[web.1]:       writable: true,
2019-12-13T18:32:27.049553+00:00 app[web.1]:       _last: true,
2019-12-13T18:32:27.049555+00:00 app[web.1]:       chunkedEncoding: false,
2019-12-13T18:32:27.049557+00:00 app[web.1]:       shouldKeepAlive: false,
2019-12-13T18:32:27.049559+00:00 app[web.1]:       useChunkedEncodingByDefault: false,
2019-12-13T18:32:27.049561+00:00 app[web.1]:       sendDate: false,
2019-12-13T18:32:27.049563+00:00 app[web.1]:       _removedConnection: false,
2019-12-13T18:32:27.049566+00:00 app[web.1]:       _removedContLen: false,
2019-12-13T18:32:27.049568+00:00 app[web.1]:       _removedTE: false,
2019-12-13T18:32:27.049570+00:00 app[web.1]:       _contentLength: 0,
2019-12-13T18:32:27.049572+00:00 app[web.1]:       _hasBody: true,
2019-12-13T18:32:27.049574+00:00 app[web.1]:       _trailer: '',
2019-12-13T18:32:27.049576+00:00 app[web.1]:       finished: true,
2019-12-13T18:32:27.049578+00:00 app[web.1]:       _headerSent: true,
2019-12-13T18:32:27.049580+00:00 app[web.1]:       socket: [TLSSocket],
2019-12-13T18:32:27.049582+00:00 app[web.1]:       connection: [TLSSocket],
2019-12-13T18:32:27.049584+00:00 app[web.1]:       _header: 'GET /deals/v1/deal/1276965455 HTTP/1.1\r\n' +
2019-12-13T18:32:27.049586+00:00 app[web.1]:         'Accept: application/json, text/plain, */*\r\n' +
2019-12-13T18:32:27.049588+00:00 app[web.1]:         'Authorization: Bearer undefined\r\n' +
2019-12-13T18:32:27.049590+00:00 app[web.1]:         'Content-Type: application/json\r\n' +
2019-12-13T18:32:27.049592+00:00 app[web.1]:         'User-Agent: axios/0.19.0\r\n' +
2019-12-13T18:32:27.049594+00:00 app[web.1]:         'Host: api.hubapi.com\r\n' +
2019-12-13T18:32:27.049596+00:00 app[web.1]:         'Connection: close\r\n' +
2019-12-13T18:32:27.049598+00:00 app[web.1]:         '\r\n',
2019-12-13T18:32:27.049600+00:00 app[web.1]:       _onPendingData: [Function: noopPendingOutput],
2019-12-13T18:32:27.049602+00:00 app[web.1]:       agent: [Agent],
2019-12-13T18:32:27.049605+00:00 app[web.1]:       socketPath: undefined,
2019-12-13T18:32:27.049606+00:00 app[web.1]:       method: 'GET',
2019-12-13T18:32:27.049608+00:00 app[web.1]:       path: '/deals/v1/deal/1276965455',
2019-12-13T18:32:27.049610+00:00 app[web.1]:       _ended: true,
2019-12-13T18:32:27.049613+00:00 app[web.1]:       res: [IncomingMessage],
2019-12-13T18:32:27.049615+00:00 app[web.1]:       aborted: false,
2019-12-13T18:32:27.049616+00:00 app[web.1]:       timeoutCb: null,
2019-12-13T18:32:27.049618+00:00 app[web.1]:       upgradeOrConnect: false,
2019-12-13T18:32:27.049621+00:00 app[web.1]:       parser: null,
2019-12-13T18:32:27.049623+00:00 app[web.1]:       maxHeadersCount: null,
2019-12-13T18:32:27.049625+00:00 app[web.1]:       _redirectable: [Writable],
2019-12-13T18:32:27.049627+00:00 app[web.1]:       [Symbol(kNeedDrain)]: false,
2019-12-13T18:32:27.049629+00:00 app[web.1]:       [Symbol(isCorked)]: false,
2019-12-13T18:32:27.049631+00:00 app[web.1]:       [Symbol(kOutHeaders)]: [Object: null prototype]
2019-12-13T18:32:27.049633+00:00 app[web.1]:     },
2019-12-13T18:32:27.049635+00:00 app[web.1]:     data: {
2019-12-13T18:32:27.049637+00:00 app[web.1]:       status: 'error',
2019-12-13T18:32:27.049639+00:00 app[web.1]:       message: 'Any of the listed authentication credentials are missing',
2019-12-13T18:32:27.049641+00:00 app[web.1]:       correlationId: '6356f281-f9bb-4454-926e-516aaac0104f',
2019-12-13T18:32:27.049643+00:00 app[web.1]:       engagement: [Object],
2019-12-13T18:32:27.049645+00:00 app[web.1]:       requestId: 'cc696c9d-c967-47a8-9258-2dcdf39d729a'
2019-12-13T18:32:27.049647+00:00 app[web.1]:     }
2019-12-13T18:32:27.049649+00:00 app[web.1]:   },
2019-12-13T18:32:27.049651+00:00 app[web.1]:   isAxiosError: true,
2019-12-13T18:32:27.049653+00:00 app[web.1]:   toJSON: [Function]
2019-12-13T18:32:27.049655+00:00 app[web.1]: }`

**Comment by louischausse** [comment]
update

after many hours of debugging, the problem seems to be related to the fact that the tokens are tied to a user/session id so when my apps try to refresh the token after a webhook event it is considered as "another user/session" and the token can't be refreshed.

I'm not sure this the problem, but this is my best bet for now.

Do you have a suggestion to work around this?

Thanks
